/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.28 from the
 * contents of Stats.xs. Do not edit this file, edit Stats.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Stats.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "const-c.inc"

static SV * init = (SV*)NULL;

typedef struct object {
  HV * metrics;
  HV * counts;
} stats_obj;

typedef stats_obj * Local__Stats;

#line 29 "Stats.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 173 "Stats.c"

/* INCLUDE:  Including 'const-xs.inc' from 'Stats.xs' */


XS_EUPXS(XS_Local__Stats_constant); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_constant)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 198 "Stats.c"
	SV *	sv = ST(0)
;
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Local::Stats macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Local::Stats macro %s, used",
				   s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Local::Stats macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 275 "Stats.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'Stats.xs' from 'const-xs.inc' */


XS_EUPXS(XS_Local__Stats_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, code");
    {
	SV *	code = ST(1)
;
	Local__Stats	RETVAL;
	char *	class = (char *)SvPV_nolen(ST(0))
;
#line 27 "Stats.xs"
    RETVAL = calloc (1, sizeof(stats_obj));
    if (! RETVAL) {
      croak ("No memory for %s", class);
    }
    RETVAL->metrics = newHV();
    RETVAL->counts = newHV();
    if (init == (SV*)NULL)
        init = newSVsv(code);
    else
        SvSetSV(init, code);
#line 308 "Stats.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	    sv_setref_pv(RETVALSV, "Local::Stats", (void*)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Local__Stats_add); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_add)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "stats, name, num");
    {
	Local__Stats	stats;
	char *	name = (char *)SvPV_nolen(ST(1))
;
	float	num = (float)SvNV(ST(2))
;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Local::Stats")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    stats = INT2PTR(Local__Stats,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not of type %s",
			"Local::Stats::add",
			"stats", "Local::Stats")
;
#line 46 "Stats.xs"
    if (hv_exists(stats->metrics, name, strlen(name))) {
      int count = SvIV(*(hv_fetch(stats->counts, name, strlen(name), 0))) + 1;
      hv_store(stats->counts, name, strlen(name), newSViv(count), 0);
      HV * save_metr = (HV *)(SvRV(*(hv_fetch(stats->metrics, name, strlen(name), 0))));
      HV * metr = newHV();
      if(hv_exists(save_metr, "cnt", 3)) {
        hv_store(metr, "cnt", 3, newSViv(count), 0);
      }
      if(hv_exists(save_metr, "min", 3)) {
        float min = SvNV(*(hv_fetch(save_metr, "min", 3, 0)));
        if (min > num) {
          hv_store(metr, "min", 3, newSVnv(num), 0);
        } else {
          hv_store(metr, "min", 3, newSVnv(min), 0);
        }
      }
      if(hv_exists(save_metr, "max", 3)) {
        float max = SvNV(*(hv_fetch(save_metr, "max", 3, 0)));
        if (max < num) {
          hv_store(metr, "max", 3, newSVnv(num), 0);
        } else {
          hv_store(metr, "max", 3, newSVnv(max), 0);
        }
      }
      if(hv_exists(save_metr, "sum", 3)) {
        hv_store(metr, "sum", 3, newSVnv(SvNV(*(hv_fetch(save_metr, "sum", 3, 0))) + num), 0);
      }
      if(hv_exists(save_metr, "avg", 3)) {
        hv_store(metr, "avg", 3, newSVnv((SvNV(*(hv_fetch(save_metr, "avg", 3, 0)))*(count-1) + num)/count), 0);
      }
      hv_store(stats->metrics, name, strlen(name), newRV((SV *)metr), 0);
    } else {
      int count;
      ENTER;
      SAVETMPS;
      PUSHMARK(SP);
      EXTEND(SP, 5);
      mPUSHp(name, strlen(name));
      PUTBACK;
      count = call_sv(init, G_ARRAY);
      SPAGAIN;
      if (count > 5)
        croak("Only cnt, max, min, avg or sum in metric!\n");
      HV* metr = (HV *)sv_2mortal((SV *)newHV());
      for (int i = 0; i < count; i++) {
        char * str = POPp;
        int empty = 1;
        if (!strcmp(str,"cnt")) {
          hv_store(metr, "cnt", 3, newSViv(1), 0);
          empty = 0;
        }
        if (!strcmp(str,"min")) {
          hv_store(metr, "min", 3, newSVnv(num), 0);
          empty = 0;
        }
        if (!strcmp(str,"max")) {
          hv_store(metr, "max", 3, newSVnv(num), 0);
          empty = 0;
        }
        if (!strcmp(str,"sum")) {
          hv_store(metr, "sum", 3, newSVnv(num), 0);
          empty = 0;
        }
        if (!strcmp(str,"avg")) {
          hv_store(metr, "avg", 3, newSVnv(num), 0);
          empty = 0;
        }
        if(!empty) {
          hv_store(stats->counts, name, strlen(name), newSViv(1), 0);
          hv_store(stats->metrics, name, strlen(name), newRV((SV *)metr), 0);
        }
      }
      FREETMPS;
      LEAVE;
    }
#line 418 "Stats.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Local__Stats_stats); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Local__Stats_stats)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "stats");
    {
	Local__Stats	stats;
	SV *	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Local::Stats")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    stats = INT2PTR(Local__Stats,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not of type %s",
			"Local::Stats::stats",
			"stats", "Local::Stats")
;
#line 125 "Stats.xs"
      RETVAL = newRV((SV *)stats->metrics);
#line 445 "Stats.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Local__Stats); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Local__Stats)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Local::Stats::constant", XS_Local__Stats_constant);
        newXS_deffile("Local::Stats::new", XS_Local__Stats_new);
        newXS_deffile("Local::Stats::add", XS_Local__Stats_add);
        newXS_deffile("Local::Stats::stats", XS_Local__Stats_stats);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

