CREATE TABLE users (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    hash VARCHAR(31) NOT NULL
) DEFAULT CHARSET utf8;

CREATE TABLE albums (
    id INT UNIQUE KEY AUTO_INCREMENT NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    band VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    PRIMARY KEY (user_name, title, band)
) DEFAULT CHARSET utf8;
